# Generated by Django 5.2.3 on 2025-07-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
